### ISSUE TITLE
Requires Python 3.11 or later due to dependency upon dataclass_transform

### ISSUE THREAD

**Issue by samhooke** [sassanh/python-immutable#1]
Thank you for creating this package! I found this issue whilst attempting to use your [python-debouncer](https://github.com/sassanh/python-debouncer) package, which looks ideal for my project needs. Unfortunately it appears that `dataclass_transform` requires Python 3.11 or later, and since `python-debouncer` depends upon `python-immutable`, that is affected too.

# Expected behaviour

The requirements state "Python 3.9 or later", so I expected to be able to use this package for an application running on Python 3.10.

# Actual behaviour

When using this dependency on Python 3.10, I get the following error:

```
Traceback (most recent call last):
...snip...
  File "/home/snip/python3.10/site-packages/debouncer/__init__.py", line 1, in <module>
    from .debounce import debounce, DebounceOptions
  File "/home/snip/python3.10/site-packages/debouncer/debounce.py", line 22, in <module>
    from immutable import Immutable
  File "/home/snip/python3.10/site-packages/immutable/__init__.py", line 1, in <module>
    from .main import *
  File "/home/snip/python3.10/site-packages/immutable/main.py", line 5, in <module>
    from typing import (
ImportError: cannot import name 'dataclass_transform' from 'typing' (/usr/lib/python3.10/typing.py)
```

From looking at [PEP 681](https://peps.python.org/pep-0681/), it appears `dataclass_transform` was not added until Python 3.11?

**Comment by sassanh** [comment]
I think I should be able to make it 3.10 compatible, I will have time to work on it early March.

**Comment by sassanh** [comment]
Please check version 1.0.4, it should work with python 3.9, I will update python-debouncer soon

**Comment by samhooke** [comment]
I can verify that `python-immutable==1.0.4` works on Python 3.10.

First, using `python-immutable==1.0.0` on Python 3.10 shows the original issue:

```console
$ poetry run python
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

```python
>>> from immutable import immutable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/snip/python3.10/site-packages/immutable/__init__.py", line 1, in <module>
    from .main import *
  File "/home/snip/python3.10/site-packages/immutable/main.py", line 5, in <module>
    from typing import (
ImportError: cannot import name 'dataclass_transform' from 'typing' (/usr/lib/python3.10/typing.py)
```

Upgrading to `python-immutable==1.0.4` shows the issue has been fixed:

```console
$ poetry add python-immutable==1.0.4

Updating dependencies
Resolving dependencies... (4.5s)

Package operations: 0 installs, 1 update, 0 removals

  - Updating python-immutable (1.0.0 -> 1.0.4)

Writing lock file
```

```console
$ poetry run python
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

```python
>>> from immutable import immutable
>>> # No error!
```

Thank you! ⭐
